### ISSUE TITLE
Kingdoms support

### ISSUE THREAD

**Issue by ltcrazyman** [MarkehMe/FreshWilderness#2]
i was wondering if you could add support for kingdoms, https://www.spigotmc.org/resources/kingdoms-battle-for-land-might-and-glory-1-8-8-1-11.11833/

**Comment by MarkehMe** [comment]
As this as a paid plugin I can't get it. However if you're able to email me through a copy of the plugin for development purposes I can add support.

My email is: markwilliamhughes1@gmail.com

**Comment by MarkehMe** [comment]
Done in 90001cf3b84cffca483d68a328cfef1e7bdea2d8, will be in the next release.
